# -*- mode: ruby -*-
# vi: set ft=ruby :

# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
# Version of this project 0.0.1
#
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  # config.ssh.insert_key = false
  # config.vm.hostname = "runbot.vauxoo.com"


  # The xenial box doesn't have python preinstalled, so we need to install it before
  # executing the ansible playbooks:
  config.vm.provision "shell",
    inline: "sudo apt-get update && sudo apt-get install python -y"

  # Full provisioning with ansible
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "../../ansible/provision-runbot.yml"
    ansible.extra_vars = {
        domain: "runbot.vauxoo.com",
        regex_domain: "~^(.*)\.runbot\.vauxoo\.colima$"
      }
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
